sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic002.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic003.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic004.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic006.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic007.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic010.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic011.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic012.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic014.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic016.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic017.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic018.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic019.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic020.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic021.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic022.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic023.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic024.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic025.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic026.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic027.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic028.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic029.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic030.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic031.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic032.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic033.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic034.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic035.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic036.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic037.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic038.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic039.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic040.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic041.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic042.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic043.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic044.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic045.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic047.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic049.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic050.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic051.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic052.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic053.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic055.html
sed -ibackup -r 's_https://www.ctspedia.org/wiki/pub/CTSpedia/([0-9a-zA-Z]+)/([0-9a-zA-Z]+)._https://www.ctspedia.org/CTSpedia/\1.attachments/\2._'g StatToolsTopic058.html

